version: "3"

volumes:
    synergy_test_db_sql3:
    
services:
    synergy_test:
        build: backend/django_rest/
        ports:
            - 8001:8000
        volumes:
            - synergy_test_db_sql3
